const ORDER_STATES = {
  NEW: 'NEW',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAID: 'PAID',
  FULLFILLED: 'FULLFILLED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED',
};

const PAYMENT_STATES = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  FULLFILLED: 'FULLFILLED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
};

const INVOICE_STATES = {
  PENDING: 'PENDING',
  CREATED: 'CREATED',
  SENT: 'SENT',
  CANCELLED: 'CANCELLED',
};

export {
  ORDER_STATES,
  PAYMENT_STATES,
  INVOICE_STATES,
};